import type { ParticleFraction } from './types';

export const THRESHOLDS = {
  warn: 50,
  alert: 75,
} as const;

export const FRACTIONS: ParticleFraction[] = [
  {
    key: '0p3',
    label: '0.3 µm',
    title: 'Ultradrobne',
    maxVal: 1_200_000,
    baseReading: 820_000,
    baseFill: 68,
    speed: 0.42,
    swing: 11,
    phase: 0,
    what: 'Graniczna frakcja pyłu zawieszonego. Produkty spalania i najdrobniejsze aerozole.',
    sources: 'Spalanie paliw, ogrzewanie, dym papierosowy, smażenie.',
    health: 'Przez pęcherzyki płucne przenikają do krwiobiegu i docierają do mózgu i serca.',
    examples: 'Spaliny diesla, dym papierosowy, smog fotochemiczny, wirusy.',
    interpretation: 'wskazuje na spalanie lub dym',
  },
  {
    key: '0p5',
    label: '0.5 µm',
    title: 'Drobny aerozol',
    maxVal: 240_000,
    baseReading: 155_000,
    baseFill: 64,
    speed: 0.37,
    swing: 9,
    phase: 1.1,
    what: 'Cząstki na granicy PM ultradrobnego. Długo utrzymują się w powietrzu.',
    sources: 'Kondensacja pary, odświeżacze w sprayu, e-papierosy, silniki.',
    health: 'Penetrują pęcherzyki płucne, tworzą trwałą zawiesinę wewnątrz pomieszczeń.',
    examples: 'Mgła olejowa w kuchni, lakier do włosów, resztki e-papierosa.',
    interpretation: 'aerozol lub drobna sadza',
  },
  {
    key: '1p0',
    label: '1.0 µm',
    title: 'Pył średni PM1',
    maxVal: 45_000,
    baseReading: 26_000,
    baseFill: 57,
    speed: 0.51,
    swing: 8,
    phase: 2.3,
    what: 'Frakcja pośrednia ważna do oceny składu smogu.',
    sources: 'Intensywne spalanie, kondensacja gazów w cząstki stałe.',
    health: 'Największa powierzchnia właściwa - zbiera metale ciężkie i benzo(a)piren.',
    examples: 'Smog fotochemiczny, drobna sadza, opary chemiczne.',
    interpretation: 'aktywne źródło zanieczyszczeń spaleniowych',
  },
  {
    key: '2p5',
    label: '2.5 µm',
    title: 'PM2.5',
    maxVal: 6_000,
    baseReading: 2_800,
    baseFill: 46,
    speed: 0.33,
    swing: 7,
    phase: 0.88,
    what: 'Kluczowa frakcja smogowa i standardowy wskaźnik jakości powietrza.',
    sources: 'Niska emisja, węgiel, drewno, ruch drogowy, przemysł.',
    health: 'Docierają do oskrzeli i płuc. Długa ekspozycja = ryzyko chorób serca i płuc.',
    examples: 'Smog zimowy, dym z komina, pył z procesów przemysłowych.',
    interpretation: 'typowy smog zimowy lub niska emisja',
  },
  {
    key: '5p0',
    label: '5.0 µm',
    title: 'Bioaerozol / kurz',
    maxVal: 700,
    baseReading: 310,
    baseFill: 44,
    speed: 0.45,
    swing: 7,
    phase: 1.75,
    what: 'Cząstki mechaniczne - szybciej osiadają, nośnik alergenów.',
    sources: 'Ruch w pomieszczeniu, pylenie roślin, zwierzęta domowe.',
    health: 'Główna przyczyna kataru siennego, łzawienia, napadów astmy u alergików.',
    examples: 'Pyłki, zarodniki grzybów, roztocza, złuszczony naskórek.',
    interpretation: 'kurz i alergeny',
  },
  {
    key: '10p0',
    label: '10 µm',
    title: 'PM10 gruby',
    maxVal: 60,
    baseReading: 22,
    baseFill: 37,
    speed: 0.29,
    swing: 6,
    phase: 3.2,
    what: 'Najgrubsza frakcja PMS5003 - pył drogowy i mechaniczny.',
    sources: 'Ścieranie opon i hamulców, budowy, pylenie dróg, wiatr.',
    health: 'Powoduje kaszel, suchość w gardle, podrażnienie spojówek.',
    examples: 'Kurz drogowy, pył z budowy, piasek, popiół.',
    interpretation: 'pył mechaniczny i osad',
  },
];
